'use strict';
(async()=>{
 const B=window.Bunty,e=B.escape,m=B.money,api=B.api,root=document.querySelector('#admin-root');let catalog,orders=[];
 const route=location.pathname.replace(/\/$/,'');
 if(route==='/admin/login'){
  root.innerHTML='<section class="admin-login"><img src="/assets/logo.jpg" alt="Bunty سجی"><h1>ADMIN LOGIN</h1><form id="login" class="system-form"><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="form-error" role="alert"></p><button class="button" type="submit">SIGN IN</button></form><p class="admin-notice">Use the Supabase Auth account assigned an active admin profile. There are no default credentials.</p><a href="/">Back to website ↗</a></section>';
  const form=document.querySelector('#login');form.onsubmit=async ev=>{ev.preventDefault();const button=form.querySelector('button');button.disabled=true;document.querySelector('#login-error').textContent='';try{await api('/api/auth/login',{method:'POST',body:{email:form.elements.email.value,password:form.elements.password.value}});location.assign('/admin/orders');}catch(err){document.querySelector('#login-error').textContent=err.message;button.disabled=false;}};return;
 }
 let user;try{user=await api('/api/auth/me');}catch(err){if([401,403].includes(err.status)){location.replace('/admin/login');return;}root.innerHTML=`<section class="section"><p class="form-error">${e(err.message)}</p><a href="/admin/login">Admin login</a></section>`;return;}
 const links=[['/admin','Dashboard'],['/admin/orders','Orders'],['/admin/menu','Menu'],['/admin/categories','Categories'],['/admin/delivery-zones','Delivery zones'],['/admin/homepage','Homepage'],['/admin/promotions','Deals & vouchers'],['/admin/settings','Settings']];
 root.innerHTML=`<div class="admin-layout"><aside class="admin-sidebar"><a class="brand" href="/"><img src="/assets/logo.jpg" alt=""><span>Bunty<span lang="ur" dir="rtl">سجی</span></span></a><nav aria-label="Admin navigation">${links.map(([url,label])=>`<a href="${url}" ${route===url?'aria-current="page"':''}>${label}</a>`).join('')}</nav><button id="logout">LOG OUT</button></aside><section class="admin-main"><p class="admin-notice">${e(user.email)} · ${e(user.role)}</p><h1>${e(links.find(([url])=>url===route)?.[1]||'Dashboard')}</h1><p id="admin-message" role="status"></p><div id="admin-content"></div></section></div>`;
 const content=document.querySelector('#admin-content'),message=document.querySelector('#admin-message');
 function notice(text,error=false){message.textContent=text;message.className=error?'form-error':'form-success';}
 async function attempt(work){try{await work();}catch(err){notice(err.message,true);if(err.status===401)location.assign('/admin/login');}}
 document.querySelector('#logout').onclick=()=>attempt(async()=>{await api('/api/auth/logout',{method:'POST'});location.assign('/admin/login');});
 const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${e(value)}" ${extra}></label>`;
 const check=(name,label,value)=>`<label class="check-label"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;
 function rowButton(action,id,label,danger=false){return `<button type="button" data-action="${action}" data-id="${e(id)}" ${danger?'class="danger"':''}>${label}</button>`;}
 async function refreshCatalog(){catalog=await api('/api/admin/catalog');}
 function formSave(form,work){form.addEventListener('submit',async ev=>{ev.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type=submit]');button.disabled=true;notice('Saving…');try{await work(new FormData(form));notice('Saved successfully.');}catch(err){notice(err.message,true);}finally{button.disabled=false;}});}
 const bool=(f,name)=>f.get(name)==='on';
 async function renderDashboard(){orders=(await api('/api/admin/orders')).orders;const summary=await api('/api/admin/order-summary');await refreshCatalog();content.innerHTML=`<div class="admin-metrics"><article>Open orders<strong>${summary.open_orders}</strong></article><article>Menu items<strong>${catalog.items.length}</strong></article><article>Active delivery zones<strong>${catalog.zones.filter(z=>z.active).length}</strong></article></div><p><a class="button" href="/admin/orders">OPEN ORDER DESK →</a></p><h2>Recent orders</h2>${ordersTable(orders.slice(0,10))}<p class="admin-notice">The order list is paginated across all orders. Order details retain the prices charged when each order was placed.</p><p><a class="text-link" href="/admin/orders">MANAGE ORDERS ↗</a></p>`;}
 const desk=window.OrderDesk.create({api,e,m,content,notice});
 function ordersTable(data){return desk.cards(data);}
 async function renderOrders(){await desk.render();}
 async function renderMenu(){await refreshCatalog();content.innerHTML=`<div class="admin-toolbar"><button id="new-item" class="button">ADD FOOD ITEM</button><label>Search menu <input id="menu-search" type="search"></label></div><div id="editor"></div><div id="menu-table"></div>`;function table(){const q=document.querySelector('#menu-search').value.toLowerCase();document.querySelector('#menu-table').innerHTML=`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Dish</th><th>Category</th><th>Prices</th><th>Available</th><th>Actions</th></tr></thead><tbody>${catalog.items.filter(i=>i.name.toLowerCase().includes(q)).map(i=>`<tr><td>${e(i.name)}</td><td>${e(catalog.categories.find(c=>c.id===i.category_id)?.name||'')}</td><td>${i.variants.filter(v=>v.available).map(v=>`${e(v.name)}: ${m(v.price)}`).join('<br>')}</td><td>${i.available?'Yes':'No'}</td><td>${rowButton('edit-menu',i.id,'Edit')}${rowButton('delete-menu',i.id,'Delete',true)}</td></tr>`).join('')}</tbody></table></div>`;}table();document.querySelector('#menu-search').oninput=table;document.querySelector('#new-item').onclick=()=>editMenu();}
 function optionRow(v={name:'',price:0,available:true}){return `<div class="option-row" data-option-id="${e(v.id||'')}"><label>Name<input data-option-name value="${e(v.name)}" required maxlength="100"></label><label>Price<input data-option-price type="number" value="${v.price}" min="0" max="1000000" step="0.01" required></label><label class="check-label"><input data-option-available type="checkbox" ${v.available?'checked':''}>Available</label><button type="button" data-remove-option>Remove</button></div>`;}
 function editMenu(id){const item=catalog.items.find(i=>i.id===id)||{name:'',category_id:catalog.categories[0]?.id||'',description:'',image_url:'',available:true,featured:false,sort_order:0,variants:[{name:'Regular',price:0,available:true}],addons:[]};const editor=document.querySelector('#editor');editor.innerHTML=`<section class="admin-editor"><h2>${id?'Edit dish':'New dish'}</h2><form id="menu-form" class="system-form">${field('name','Dish name',item.name,'text','required maxlength="160"')}<label>Category<select aria-label="Category" name="category_id" required><option value="">Choose a category</option>${catalog.categories.map(c=>`<option value="${c.id}" ${c.id===item.category_id?'selected':''}>${e(c.name)}${c.active?'':' (inactive)'}</option>`).join('')}</select></label><label>Description<textarea name="description" maxlength="1500">${e(item.description)}</textarea></label>${field('image_url','Image URL',item.image_url,'text','maxlength="2000"')}<label>Upload food photo (JPEG, PNG, WebP; max 5 MB)<input id="photo-upload" type="file" accept="image/jpeg,image/png,image/webp"></label><p id="upload-status" role="status"></p><img id="photo-preview" class="admin-image" src="${e(item.image_url||'/assets/logo.jpg')}" alt="Food image preview">${check('available','Dish is available',item.available)}${check('featured','Featured dish',item.featured)}${field('sort_order','Display order',item.sort_order,'number','min="0" max="9999" required')}<h3>Portions / variants</h3><div id="variant-list" class="option-list">${item.variants.map(optionRow).join('')}</div><button type="button" data-add-option="variant-list">ADD VARIANT</button><h3>Optional add-ons</h3><div id="addon-list" class="option-list">${item.addons.map(optionRow).join('')}</div><button type="button" data-add-option="addon-list">ADD ADD-ON</button><button class="button" type="submit">SAVE DISH</button></form></section>`;const form=document.querySelector('#menu-form');editor.scrollIntoView({block:'start',behavior:'instant'});
  form.addEventListener('click',ev=>{const add=ev.target.closest('[data-add-option]'),remove=ev.target.closest('[data-remove-option]');if(add)document.getElementById(add.dataset.addOption).insertAdjacentHTML('beforeend',optionRow());if(remove)remove.closest('.option-row').remove();});
  document.querySelector('#photo-upload').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;const status=document.querySelector('#upload-status'),save=form.querySelector('[type=submit]');save.disabled=true;status.textContent='Uploading…';try{const data=new FormData();data.append('image',file);const result=await api('/api/admin/upload',{method:'POST',body:data});form.elements.image_url.value=result.url;document.querySelector('#photo-preview').src=result.url;status.textContent='Photo uploaded. Save the dish to apply it.';}catch(err){status.textContent=err.message;}finally{save.disabled=false;}};
  function options(list){return [...document.querySelectorAll(`#${list} .option-row`)].map(row=>({...row.dataset.optionId?{id:row.dataset.optionId}:{},name:row.querySelector('[data-option-name]').value,price:Number(row.querySelector('[data-option-price]').value),available:row.querySelector('[data-option-available]').checked}));}
  formSave(form,async f=>{await api('/api/admin/menu',{method:'POST',body:{...(id?{id}:{}),name:f.get('name'),category_id:f.get('category_id'),description:f.get('description'),image_url:f.get('image_url'),available:bool(f,'available'),featured:bool(f,'featured'),sort_order:Number(f.get('sort_order')),variants:options('variant-list'),addons:options('addon-list')}});await renderMenu();});
 }
 async function renderSimple(type){const zones=type==='delivery-zones',records=await api(`/api/admin/${type}`);content.innerHTML=`<button id="new-record" class="button">ADD ${zones?'DELIVERY ZONE':'CATEGORY'}</button><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Name</th>${zones?'<th>Fee / minimum / ETA</th>':'<th>Sort order</th>'}<th>Active</th><th>Actions</th></tr></thead><tbody>${records.map(r=>`<tr><td>${e(r.name)}</td><td>${zones?`${m(r.delivery_fee)} / ${m(r.minimum_order)} / ${r.estimated_minutes} min`:r.sort_order}</td><td>${r.active?'Yes':'No'}</td><td>${rowButton('edit-record',r.id,'Edit')}${rowButton('delete-record',r.id,'Delete',true)}</td></tr>`).join('')||'<tr><td colspan="4">No records yet. Add one to begin.</td></tr>'}</tbody></table></div><div id="editor"></div>`;
  function edit(id){const r=records.find(x=>x.id===id)||{name:'',sort_order:0,delivery_fee:0,minimum_order:0,estimated_minutes:45,active:true};document.querySelector('#editor').innerHTML=`<section class="admin-editor"><h2>${id?'Edit':'Create'} ${zones?'delivery zone':'category'}</h2><form id="record-form" class="system-form">${field('name','Name',r.name,'text','required maxlength="80"')}${zones?field('delivery_fee','Delivery fee (Rs.)',r.delivery_fee,'number','min="0" max="1000000" step="0.01" required')+field('minimum_order','Minimum order (Rs.)',r.minimum_order,'number','min="0" max="1000000" step="0.01" required')+field('estimated_minutes','Estimated delivery minutes',r.estimated_minutes,'number','min="5" max="1440" required'):field('sort_order','Display order',r.sort_order,'number','min="0" max="9999" required')}${check('active','Active',r.active)}<button class="button" type="submit">SAVE ${zones?'ZONE':'CATEGORY'}</button></form></section>`;formSave(document.querySelector('#record-form'),async f=>{const body={name:f.get('name'),active:bool(f,'active'),...(zones?{delivery_fee:Number(f.get('delivery_fee')),minimum_order:Number(f.get('minimum_order')),estimated_minutes:Number(f.get('estimated_minutes'))}:{sort_order:Number(f.get('sort_order'))})};await api(`/api/admin/${type}${id?'/'+id:''}`,{method:id?'PUT':'POST',body});await renderSimple(type);});document.querySelector('#editor').scrollIntoView({block:'start',behavior:'instant'});}
  document.querySelector('#new-record').onclick=()=>edit();content.onclick=ev=>{const button=ev.target.closest('[data-action]');if(!button)return;if(button.dataset.action==='edit-record')edit(button.dataset.id);if(button.dataset.action==='delete-record'&&confirm(`Delete this ${zones?'zone':'category'}? Categories containing dishes must be emptied first.`))attempt(async()=>{await api(`/api/admin/${type}/${button.dataset.id}`,{method:'DELETE'});await renderSimple(type);notice('Deleted.');});};
 }
 async function renderSettings(){await refreshCatalog();const s=catalog.settings;content.innerHTML=`<form id="settings-form" class="system-form admin-editor">${field('name','Restaurant name',s.name,'text','required maxlength="160"')}${field('phone','Phone',s.phone,'tel','required maxlength="30"')}${field('whatsapp','WhatsApp (international number)',s.whatsapp,'tel','maxlength="30"')}${field('whatsapp2','Second WhatsApp number',s.whatsapp2,'tel','maxlength="30"')}${field('email','Restaurant email',s.email,'email','maxlength="254"')}<label>Address<textarea name="address" minlength="5" maxlength="500" required>${e(s.address)}</textarea></label><label>Opening hours<textarea name="opening_hours" maxlength="1000" required>${e(s.opening_hours)}</textarea></label>${field('minimum_preparation_minutes','Minimum preparation time (minutes)',s.minimum_preparation_minutes,'number','min="5" max="240" required')}${check('delivery_enabled','Accept delivery orders',s.delivery_enabled)}${check('takeaway_enabled','Accept takeaway orders',s.takeaway_enabled)}<p class="admin-notice">Create real active delivery zones before enabling delivery. Opening hours are displayed to customers; use these switches to pause acceptance when the kitchen is closed.</p>${['instagram','facebook','tiktok','youtube'].map(n=>field(n,n[0].toUpperCase()+n.slice(1)+' URL',s[n],'url')).join('')}<button class="button" type="submit">SAVE SETTINGS</button></form>`;formSave(document.querySelector('#settings-form'),async f=>{const body=Object.fromEntries(['name','phone','whatsapp','whatsapp2','email','address','opening_hours','instagram','facebook','tiktok','youtube'].map(k=>[k,f.get(k)]));body.minimum_preparation_minutes=Number(f.get('minimum_preparation_minutes'));body.delivery_enabled=bool(f,'delivery_enabled');body.takeaway_enabled=bool(f,'takeaway_enabled');await api('/api/admin/settings',{method:'PUT',body});});}
 const storefront=window.AdminStorefront({api,e,m,content,notice,field,check,formSave});
 root.addEventListener('click',ev=>{const button=ev.target.closest('[data-action]');if(!button)return;const {action,id}=button.dataset;if(action==='edit-menu')editMenu(id);if(action==='delete-menu'&&confirm('Delete this food item? Existing order records will keep their original names and prices.'))attempt(async()=>{await api(`/api/admin/menu/${id}`,{method:'DELETE'});await renderMenu();notice('Dish deleted.');});});
 await attempt(async()=>{if(route==='/admin/homepage')await storefront.homepage();else if(route==='/admin/promotions')await storefront.promotions();else if(route==='/admin/orders')await renderOrders();else if(route==='/admin/menu')await renderMenu();else if(route==='/admin/categories')await renderSimple('categories');else if(route==='/admin/delivery-zones')await renderSimple('delivery-zones');else if(route==='/admin/settings')await renderSettings();else await renderDashboard();});

})();
