'use strict';
window.Commerce=(()=>{
 const B=window.Bunty,e=B.escape,m=B.money;
 function lines(){return B.entries().map(x=>`<div class="checkout-line"><div><strong>${e(x.item?.name||'Removed dish')}</strong><p>${e(x.variant?.name||'Unavailable portion')}${x.addons.length?' · '+x.addons.map(a=>e(a?.name||'Removed add-on')).join(', '):''}</p>${!x.available?'<p class="form-error">Unavailable: remove this selection.</p>':''}<div class="quantity"><button type="button" data-check-qty="${x.index}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${x.quantity}</span><button type="button" data-check-qty="${x.index}" data-delta="1" aria-label="Increase quantity">+</button><button type="button" data-check-remove="${x.index}">Remove</button></div></div><strong>${m(x.total)}</strong></div>`).join('');}
 function newToken(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');}
 async function checkout(){
  const main=document.querySelector('#main'),catalog=await B.ready;
  main.innerHTML='<section class="page-intro"><span class="eyebrow">YOUR BUNTY SAJJI ORDER</span><h1>CHECKOUT.</h1><p>Choose delivery or takeaway. Pay cash when your food arrives or when you collect it.</p></section>';
  if(!catalog){main.innerHTML+=`<section class="section"><p class="form-error">${e(B.error)}</p><a href="/menu/">Back to menu</a></section>`;return;}
  const {settings,zones}=catalog;
  if(!B.cart.length){main.innerHTML+='<section class="section"><p>Your bag is empty.</p><a class="button" href="/menu/">EXPLORE MENU ↗</a></section>';return;}
  const delivery=settings.delivery_enabled&&zones.some(z=>z.active),takeaway=settings.takeaway_enabled;
  main.innerHTML+=`<section class="section checkout-grid"><form id="checkout-form" class="system-form"><h2>Your details</h2><fieldset><legend>How would you like your order?</legend><label><input type="radio" name="fulfillment" value="delivery" ${delivery?'checked':'disabled'}> Delivery ${!delivery?'(unavailable)':''}</label><label><input type="radio" name="fulfillment" value="takeaway" ${!delivery&&takeaway?'checked':''} ${!takeaway?'disabled':''}> Takeaway ${!takeaway?'(unavailable)':''}</label></fieldset><label>Full name<input name="customer_name" required minlength="2" maxlength="100" autocomplete="name"></label><label>Phone number<input name="phone" type="tel" required pattern="[+0-9 ()-]{7,25}" maxlength="25" autocomplete="tel"></label><div id="delivery-fields"><label>Delivery area<select aria-label="Delivery area" name="zone_id"><option value="">Choose your area</option>${zones.filter(z=>z.active).map(z=>`<option value="${e(z.id)}">${e(z.name)} · ${m(z.delivery_fee)}</option>`).join('')}</select></label><p id="zone-information"></p><label>Full delivery address<textarea name="address" minlength="5" maxlength="500" autocomplete="street-address"></textarea></label><label>Landmark (optional)<input name="landmark" maxlength="200"></label></div><div id="pickup-fields"><label>Pickup timing<select aria-label="Pickup timing" name="pickup_mode"><option value="asap">As soon as possible</option><option value="scheduled">Schedule a pickup</option></select></label><label id="pickup-time-field">Pickup time (Sialkot, Pakistan)<input name="pickup_at" type="datetime-local"></label><p>Allow at least ${settings.minimum_preparation_minutes} minutes. Scheduled pickup is available within the next 7 days.</p></div><label>Delivery or pickup instructions (optional)<textarea name="instructions" maxlength="1000"></textarea></label><p class="payment-notice" id="payment-notice"></p><p class="form-error" id="checkout-error" role="alert"></p><button class="button" type="submit" id="place-order" disabled>PLACE ORDER</button><p class="caption">Submitting places a real cash order with the restaurant. Keep the private confirmation link to track it.</p></form><aside class="order-summary-panel"><h2>Your order</h2><div id="checkout-lines">${lines()}</div><div id="checkout-totals" aria-live="polite"></div><a class="text-link" href="/menu/">ADD MORE FOOD ↗</a></aside></section>`;
  const form=document.querySelector('#checkout-form'),button=document.querySelector('#place-order'),error=document.querySelector('#checkout-error');let quote=null,version=0,submitting=false,pending=null;
  try{pending=JSON.parse(sessionStorage.getItem('bunty-pending-order')||'null');}catch{/* Fresh order. */}
  function input(){const f=new FormData(form);return {items:B.cart,fulfillment:f.get('fulfillment'),zone_id:f.get('fulfillment')==='delivery'?(f.get('zone_id')||null):null,pickup_mode:f.get('fulfillment')==='takeaway'?f.get('pickup_mode'):'asap',pickup_at:f.get('fulfillment')==='takeaway'&&f.get('pickup_mode')==='scheduled'&&f.get('pickup_at')?new Date(f.get('pickup_at')+':00+05:00').toISOString():null};}
  async function refresh(){const revision=++version;quote=null;button.disabled=true;error.textContent='';const payload=input();const isDelivery=payload.fulfillment==='delivery';document.querySelector('#delivery-fields').hidden=!isDelivery;document.querySelector('#pickup-fields').hidden=isDelivery;form.elements.address.required=isDelivery;form.elements.zone_id.required=isDelivery;document.querySelector('#pickup-time-field').hidden=payload.pickup_mode!=='scheduled';form.elements.pickup_at.required=!isDelivery&&payload.pickup_mode==='scheduled';document.querySelector('#payment-notice').textContent=isDelivery?'Payment: Cash on Delivery':'Payment: Cash on Pickup';const zone=zones.find(z=>z.id===payload.zone_id);document.querySelector('#zone-information').textContent=zone?`Minimum ${m(zone.minimum_order)} · Estimated ${zone.estimated_minutes} minutes`:'';document.querySelector('#checkout-lines').innerHTML=lines();const totals=document.querySelector('#checkout-totals');totals.innerHTML=`<p>Subtotal <strong>${m(B.subtotal())}</strong></p><p>Delivery <strong>${isDelivery?(zone?m(zone.delivery_fee):'Choose an area'):m(0)}</strong></p><p>Total <strong>${m(B.subtotal()+(isDelivery?Number(zone?.delivery_fee||0):0))}</strong></p>`;
   if(!payload.fulfillment){error.textContent='Ordering is currently paused.';return;}if(!B.cart.length){error.textContent='Your bag is empty.';return;}if(B.entries().some(x=>!x.available)){error.textContent='Remove unavailable selections before ordering.';return;}if(isDelivery&&!zone)return;if(payload.pickup_mode==='scheduled'&&!payload.pickup_at)return;
   try{const result=await B.api('/api/quote',{method:'POST',body:payload});if(revision!==version)return;quote=result;totals.innerHTML=`<p>Subtotal <strong>${m(quote.subtotal)}</strong></p><p>Delivery <strong>${m(quote.delivery_fee)}</strong></p><p class="grand-total">Total <strong>${m(quote.total)}</strong></p><p>Estimated ${quote.estimated_minutes} minutes${payload.pickup_mode==='scheduled'?' (scheduled pickup selected)':''}</p>`;button.disabled=submitting;}catch(err){if(revision===version)error.textContent=err.message;}
  }
  form.addEventListener('change',ev=>{if(['fulfillment','zone_id','pickup_mode','pickup_at'].includes(ev.target.name))refresh();});
  document.querySelector('#checkout-lines').addEventListener('click',ev=>{if(submitting)return;const q=ev.target.closest('[data-check-qty]'),r=ev.target.closest('[data-check-remove]');if(q)B.quantity(+q.dataset.checkQty,+q.dataset.delta);if(r)B.remove(+r.dataset.checkRemove);if(q||r)refresh();});
  form.addEventListener('submit',async ev=>{ev.preventDefault();if(submitting||!quote||!form.reportValidity())return;submitting=true;button.disabled=true;button.textContent='PLACING ORDER…';error.textContent='';const data=new FormData(form);const payload={...input(),customer_name:data.get('customer_name'),phone:data.get('phone'),address:data.get('address')||'',landmark:data.get('landmark')||'',instructions:data.get('instructions')||'',expected_total:Number(quote.total)};const signature=JSON.stringify(payload);if(!pending||pending.signature!==signature)pending={signature,request_key:crypto.randomUUID(),tracking_token:newToken()};try{sessionStorage.setItem('bunty-pending-order',JSON.stringify(pending));}catch{/* Retry retained in memory. */}
   try{const result=await B.api('/api/orders',{method:'POST',body:{...payload,request_key:pending.request_key,tracking_token:pending.tracking_token}});const link=`/order/${encodeURIComponent(result.order_number)}#${pending.tracking_token}`;try{localStorage.setItem('bunty-last-order',link);sessionStorage.removeItem('bunty-pending-order');}catch{/* Confirmation still works. */}B.clear();location.assign(link);}catch(err){error.textContent=err.message;submitting=false;button.disabled=false;button.textContent='PLACE ORDER';if(err.message.includes('Prices changed')){await refresh();error.textContent='Prices changed. Review the updated total and submit again to confirm.';}}
  });
  await refresh();
 }
 async function tracking(){const main=document.querySelector('#main'),number=decodeURIComponent(location.pathname.split('/')[2]||'');const token=location.hash.slice(1);main.innerHTML=`<section class="page-intro"><span class="eyebrow">YOUR PRIVATE ORDER TRACKER</span><h1>${e(number)}</h1><p>Keep this link private. It includes your order and delivery details.</p></section><section class="section"><p id="tracking-error" class="form-error" role="status"></p><div id="tracking-content"></div><button id="refresh-tracking" class="button">REFRESH STATUS</button><p class="caption">Updates automatically every 10 seconds while this page is visible.</p></section>`;
  let busy=false;async function refresh(){if(busy)return;busy=true;try{const order=await B.api(`/api/orders/${encodeURIComponent(number)}`,{headers:{Authorization:`Bearer ${token}`}});document.querySelector('#tracking-error').textContent='';const flow=['new','confirmed','preparing',order.fulfillment==='delivery'?'out_for_delivery':'ready_for_pickup','completed'];document.querySelector('#tracking-content').innerHTML=`<div class="tracking-status"><h2>${e(order.status.replaceAll('_',' '))}</h2><p>${order.fulfillment==='delivery'?'Delivery':'Takeaway'} · ${e(order.payment_method.replaceAll('_',' '))} · Payment ${e(order.payment_status)}</p></div><ol class="tracking-steps">${flow.map((s,i)=>`<li class="${i<=flow.indexOf(order.status)?'done':''}">${e(s.replaceAll('_',' '))}</li>`).join('')}</ol><div class="checkout-grid"><div><h3>Customer details</h3><p>${e(order.customer_name)} · ${e(order.phone)}</p>${order.fulfillment==='delivery'?`<p>${e(order.address)}<br>${e(order.zone_name)}<br>${e(order.landmark)}</p>`:`<p>Pickup: ${order.pickup_at?e(new Date(order.pickup_at).toLocaleString('en-PK',{timeZone:'Asia/Karachi'}))+' (Pakistan time)':'As soon as possible'}</p>`}<p>${e(order.instructions)}</p><p>Estimated ${order.estimated_minutes} minutes ${order.fulfillment==='delivery'?'for delivery':'preparation'}; the restaurant confirms timing.</p><h3>Status history</h3><ul>${order.history.sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(h=>`<li>${e(h.status.replaceAll('_',' '))} · ${e(new Date(h.created_at).toLocaleString())}</li>`).join('')}</ul></div><div class="order-summary-panel"><h3>Ordered items</h3>${order.items.map(i=>`<div class="checkout-line"><div>${i.quantity} × ${e(i.item_name)}<p>${e(i.variant_name)}${i.addons.length?' · '+i.addons.map(a=>e(a.name)).join(', '):''}</p></div><strong>${m(i.line_total)}</strong></div>`).join('')}<p>Subtotal: ${m(order.subtotal)}</p><p>Delivery: ${m(order.delivery_fee)}</p><p class="grand-total">Total: ${m(order.total)}</p></div></div>`;}catch(err){document.querySelector('#tracking-error').textContent=err.message;}finally{busy=false;}}
  document.querySelector('#refresh-tracking').onclick=refresh;await refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},10000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
 }
 return {checkout,tracking};
})();
