'use strict';
window.OrderDesk={create({api,e,m,content,notice}){
 let page=1,filter='active',search='',revision=0,timer,searchTimer,selected=null,lastData=[];
 const busy=new Set();
 const labels={new:'New order',confirmed:'Accepted',preparing:'Cooking',out_for_delivery:'Out for delivery',ready_for_pickup:'Ready for pickup',completed:'Completed',cancelled:'Cancelled'};
 const actions={confirmed:'Accept order',preparing:'Start cooking',out_for_delivery:'Send for delivery',ready_for_pickup:'Ready for pickup',completed:'Cash received · Complete'};
 const next=o=>({new:'confirmed',confirmed:'preparing',preparing:o.fulfillment==='delivery'?'out_for_delivery':'ready_for_pickup',out_for_delivery:'completed',ready_for_pickup:'completed'})[o.status];
 const time=value=>new Date(value).toLocaleString('en-PK',{timeZone:'Asia/Karachi',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});
 const phone=value=>String(value).replace(/[^+0-9]/g,'');
 function action(o){const step=next(o);return step?`<button class="desk-primary" data-desk-advance="${e(o.id)}" data-next="${step}" ${busy.has(o.id)?'disabled':''}>${busy.has(o.id)?'Saving…':actions[step]}</button>`:'<span class="desk-closed">'+(o.status==='completed'?'Cash collected':'Order cancelled')+'</span>';}
 function cards(orders){return `<div class="order-cards">${orders.map(o=>`<article class="order-ticket" data-order-id="${e(o.id)}" data-status="${e(o.status)}"><div class="ticket-top"><strong>${e(o.order_number)}</strong><span class="fulfillment-pill">${o.fulfillment==='delivery'?'Delivery':'Takeaway'}</span></div><div class="ticket-meta"><span class="order-state">${labels[o.status]}</span><time>${e(time(o.created_at))} PKT</time></div><h2>${e(o.customer_name)}</h2><a class="ticket-phone" href="tel:${e(phone(o.phone))}">Call ${e(o.phone)} ↗</a>${o.fulfillment==='delivery'?`<p class="ticket-address">${e(o.zone_name||o.address||'See delivery address')}</p>`:`<p class="ticket-address">Pickup ${o.pickup_at?e(time(o.pickup_at))+' PKT':'as soon as possible'}</p>`}<ul class="ticket-items">${(o.items||[]).slice(0,3).map(i=>`<li><b>${i.quantity}×</b> ${e(i.item_name)} <small>${e(i.variant_name)}</small></li>`).join('')}</ul>${(o.items?.length||0)>3?`<p class="small-note">+ ${o.items.length-3} more items</p>`:''}<div class="ticket-total"><span>${o.payment_status==='paid'?'Cash collected':'Cash to collect'}</span><strong>${m(o.total)}</strong></div><div class="ticket-actions">${action(o)}<button class="desk-secondary" data-desk-open="${e(o.id)}">View order</button></div></article>`).join('')}</div>`;}
 function dialog(){let d=document.querySelector('#order-dialog');if(!d){d=document.createElement('dialog');d.id='order-dialog';d.className='order-dialog';d.setAttribute('aria-labelledby','order-detail-title');document.body.append(d);d.addEventListener('click',event=>{if(event.target===d)d.close();});d.addEventListener('close',()=>{selected=null;});d.addEventListener('click',handleClick);}return d;}
 async function open(id){selected=id;const d=dialog();d.innerHTML='<p role="status">Loading order…</p>';if(!d.open)d.showModal();try{const o=await api(`/api/admin/orders/${id}`);if(selected!==id)return;renderDetail(o);}catch(err){d.innerHTML=`<p class="form-error">${e(err.message)}</p><button data-desk-close>Close</button>`;}}
 function renderDetail(o){const d=dialog();d.innerHTML=`<section id="order-detail"><div class="ticket-top"><div><small>ORDER DETAILS</small><h2 id="order-detail-title">${e(o.order_number)}</h2></div><button class="desk-close" data-desk-close aria-label="Close order">×</button></div><p class="detail-status">Current status: <strong>${e(o.status.replaceAll('_',' '))}</strong></p><div class="detail-customer"><strong>${e(o.customer_name)}</strong><a href="tel:${e(phone(o.phone))}">Call ${e(o.phone)} ↗</a></div><div class="detail-delivery"><h3>${o.fulfillment==='delivery'?'Deliver to':'Takeaway'}</h3>${o.fulfillment==='delivery'?`<p>${e(o.address)}</p><p>${e(o.zone_name||'')}${o.landmark?' · '+e(o.landmark):''}</p>`:`<p>${o.pickup_at?e(time(o.pickup_at))+' PKT':'Pickup as soon as possible'}</p>`}</div>${o.instructions?`<p class="order-note"><strong>Customer note</strong><br>${e(o.instructions)}</p>`:''}<ul class="detail-items">${o.items.map(i=>`<li><div><strong>${i.quantity} × ${e(i.item_name)}</strong><small>${e(i.variant_name)}${i.addons.length?' · '+i.addons.map(a=>e(a.name)).join(', '):''}</small></div><strong>${m(i.line_total)}</strong></li>`).join('')}</ul><p class="detail-fees">Food ${m(o.subtotal)} <span>Delivery ${m(o.delivery_fee)}</span></p>${Number(o.discount)>0?`<p class="discount-line">${e(o.promotion_name)}${o.voucher_code?" / "+e(o.voucher_code):""}: &minus;${m(o.discount)}</p>`:""}<div class="ticket-total"><span>${o.payment_status==='paid'?'Cash collected':'Cash to collect'}</span><strong>${m(o.total)}</strong></div><div class="detail-actions">${action(o)}${next(o)?`<button class="desk-cancel" data-desk-cancel="${e(o.id)}">Cancel order</button>`:''}</div>${next(o)==='completed'?'<p class="small-note">Complete only after the full cash amount has been received.</p>':''}<p class="form-error" id="desk-error" role="alert"></p><details class="order-history"><summary>Order history</summary><ul>${o.history.sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(h=>`<li>${labels[h.status]} · ${e(time(h.created_at))} PKT</li>`).join('')}</ul></details></section>`;}
 async function update(id,status){if(busy.has(id))return;if(status==='cancelled'&&!confirm('Cancel this order? This cannot be undone.'))return;busy.add(id);document.querySelectorAll(`[data-desk-advance="${id}"],[data-desk-cancel="${id}"]`).forEach(b=>b.disabled=true);notice('Saving order…');try{await api(`/api/admin/orders/${id}/status`,{method:'PATCH',body:{status}});busy.delete(id);if(selected===id){const o=await api(`/api/admin/orders/${id}`);if(selected===id)renderDetail(o);}if(document.querySelector('#desk-list'))await refresh();else location.reload();notice('Order updated.');}catch(err){notice(err.message,true);const error=document.querySelector('#desk-error');if(error)error.textContent=err.message;}finally{busy.delete(id);document.querySelectorAll(`[data-desk-advance="${id}"],[data-desk-cancel="${id}"]`).forEach(b=>b.disabled=false);}}
 function handleClick(event){const openButton=event.target.closest('[data-desk-open]'),advance=event.target.closest('[data-desk-advance]'),cancel=event.target.closest('[data-desk-cancel]');if(openButton)open(openButton.dataset.deskOpen);if(advance)update(advance.dataset.deskAdvance,advance.dataset.next);if(cancel)update(cancel.dataset.deskCancel,'cancelled');if(event.target.closest('[data-desk-close]'))dialog().close();}
 content.addEventListener('click',handleClick);
 async function refresh(){const current=++revision;const data=await api(`/api/admin/orders?page=${page}&status=${encodeURIComponent(filter)}&search=${encodeURIComponent(search)}`);if(current!==revision)return;const pages=Math.max(1,Math.ceil(data.total/data.page_size));if(page>pages){page=pages;return refresh();}lastData=data.orders;const list=document.querySelector('#desk-list');if(!list)return;list.innerHTML=data.orders.length?cards(data.orders):`<div class="desk-empty"><strong>${search?'No matching orders':'You’re all caught up'}</strong><p>${search?'Try an order number, customer name or phone.':'New orders will appear here automatically.'}</p></div>`;document.querySelector('#desk-count').textContent=`${data.total} ${filter==='active'?'active ':''}order${data.total===1?'':'s'}`;document.querySelector('#desk-updated').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});document.querySelector('#desk-pagination').innerHTML=pages>1?`<button id="desk-prev" ${page===1?'disabled':''}>Previous</button><span>Page ${page} of ${pages}</span><button id="desk-next" ${page>=pages?'disabled':''}>Next</button>`:'';document.querySelector('#desk-prev')?.addEventListener('click',()=>{page--;safeRefresh();});document.querySelector('#desk-next')?.addEventListener('click',()=>{page++;safeRefresh();});}
 async function safeRefresh(){try{await refresh();}catch(err){notice(err.message,true);if(err.status===401)location.assign('/admin/login');}}
 async function render(){content.innerHTML=`<div class="desk-heading"><p><strong id="desk-count">Loading orders…</strong><span id="desk-updated">Refreshes automatically</span></p><button class="desk-secondary" id="reload-orders">Refresh</button></div><div class="desk-controls"><div class="desk-tabs" aria-label="Order status">${[['active','Active'],['new','New'],['completed','Completed'],['','All orders']].map(([value,label])=>`<button data-desk-filter="${value}" aria-pressed="${value===filter}">${label}</button>`).join('')}</div><input type="search" id="order-search" aria-label="Find order" placeholder="Search name, phone or order number"></div><div id="desk-list" aria-live="polite"></div><div id="desk-pagination" class="desk-pagination"></div>`;content.querySelectorAll('[data-desk-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.deskFilter;page=1;revision++;content.querySelectorAll('[data-desk-filter]').forEach(b=>b.setAttribute('aria-pressed',b===button));safeRefresh();});document.querySelector('#order-search').oninput=event=>{search=event.target.value;page=1;revision++;clearTimeout(searchTimer);searchTimer=setTimeout(safeRefresh,250);};document.querySelector('#reload-orders').onclick=safeRefresh;await refresh();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden&&!busy.size)safeRefresh();},15000);}
 window.addEventListener('pagehide',()=>{clearInterval(timer);clearTimeout(searchTimer);});
 return {cards,open,render,get orders(){return lastData;}};
}};
