'use strict';
(async function startPublic(){
const B=window.Bunty;const live=await B.ready;const previewItems=window.previewMenu||[];
const items=live?live.items.map(p=>({...p,category:live.categories.find(c=>c.id===p.category_id)?.name||'',variants:p.variants.filter(v=>v.available).map(v=>[v.name,Number(v.price)]),variant_ids:p.variants.filter(v=>v.available).map(v=>v.id),image_url:p.image_url,addons:p.addons.filter(a=>a.available)})):previewItems.map(p=>({...p,available:false,variant_ids:[],addons:[],image_url:'/assets/food/'+p.image+'.webp'}));
const esc=B.escape,photo=window.foodPhoto;

const $=s=>document.querySelector(s);const money=n=>'Rs. '+n.toLocaleString('en-PK');
const border='<div class="truck-border" aria-hidden="true"></div>';const intro=(k,t,p)=>`<section class="page-intro"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></section>${border}`;
function card(p){if(!p)return '';const available=Boolean(live&&p.available&&p.variants.length);const fallbackUrl=p.fallbackImage?'/assets/food/'+p.fallbackImage+'.webp':'/assets/logo.jpg';return `<article class="food-card"><div class="card-art"><img ${photo(p.image_url||fallbackUrl)} decoding="async" alt="${esc(p.name)}" width="300" height="220" loading="lazy"><span>${esc(p.category)}</span></div><div class="food-info"><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p>${p.variants.length>1?`<label>CHOOSE YOUR PORTION<select data-variant="${esc(p.id)}" aria-label="${esc(p.name)} portion">${p.variants.map(([n,v],i)=>`<option value="${i}">${esc(n)} · ${v===null?'Ask for price':money(v)}</option>`).join('')}</select></label>`:''}${p.addons.length?`<fieldset class="addon-options"><legend>OPTIONAL ADD-ONS</legend>${p.addons.map(a=>`<label><input type="checkbox" data-addon="${a.id}">${esc(a.name)} + ${money(Number(a.price))}</label>`).join('')}</fieldset>`:''}<div class="food-bottom"><strong data-price>${p.variants[0]?.[1]!=null?money(p.variants[0][1]):'Ask for price'}</strong><button data-add="${esc(p.id)}" aria-label="Add ${esc(p.name)} to bag" ${available?'':'disabled'}>${available?'ADD +':live?'UNAVAILABLE':'OFFLINE'}</button></div></div></article>`}
const cta=`${border}<section class="cta"><span class="eyebrow">AAO JI, ROTI SHOTI KHAYEIN.</span><h2>BHUKH LAGGI?<br><em>AA JAO JI.</em></h2><a class="button" href="/menu/">FIND YOUR FAVOURITE ↗</a></section>`;
const story=`<section class="story"><div class="story-art story-food-gallery"><img ${photo("/assets/food-ai/chicken-sajji.webp")} alt="Chicken sajji with rice" loading="lazy" width="1200" height="1200"><img ${photo("/assets/food-ai/chicken-karahi.webp")} alt="Chicken karahi" loading="lazy" width="1200" height="1200"><img ${photo("/assets/food-ai/chicken-kabab.webp")} alt="Grilled chicken kebabs" loading="lazy" width="1200" height="1200"></div><div class="story-copy"><span class="eyebrow">DESI DIL SE · دیسی دل سے</span><h2>ROTI. YAARI.<br>DILDAARI.</h2><p>Some meals are better with everyone around. A platter in the middle, a little extra raita, and that one friend reaching for the last bite.</p><p>From sajji and smoky BBQ to comforting karahi, Bunty سجی’s menu has something for every appetite. Pick your favourite, pass it around, and make a meal of it.</p><a href="/menu/" class="text-link">LET’S SET THE TABLE ↗</a></div></section>`;
const deliveryZones=`<section class="section" aria-label="Delivery coverage areas"><div class="section-heading"><div><span class="eyebrow">DELIVERY COVERAGE</span><h2>FRESH FROM<br><span>ALAM CHOWK.</span></h2></div></div>${live?.settings?.delivery_enabled&&live.zones?.length?`<ul class="delivery-area-list">${live.zones.map(zone=>`<li><strong>${esc(zone.name)}</strong><span>${money(Number(zone.delivery_fee))} delivery · Minimum ${money(Number(zone.minimum_order))}</span></li>`).join('')}</ul><p class="caption">Choose your area at checkout to see the delivery charge and estimated time. Call us if your area is not listed.</p>`:'<p>Call the restaurant to confirm delivery to your area. Available delivery areas and charges appear at checkout.</p>'}</section>`;
const discovery=`<section class="discovery" aria-label="Explore food categories"><div class="discovery-heading"><span class="eyebrow">WHAT ARE YOU CRAVING?</span><span>Ajj ki khana ae?</span></div><div class="category-tiles">${[['Sajji & Rice','THE SIGNATURE','Sajji & rice'],['Karahi','STRAIGHT TO THE TABLE','Karahi'],['BBQ','FROM THE GRILL','Smoky BBQ'],['Platters','BRING YOUR PEOPLE','Sharing platters']].map(([c,k,n])=>`<a class="category-tile" href="/menu/?category=${encodeURIComponent(c)}"><div><small>${k}</small><strong>${n}</strong></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`;
const route=location.pathname.split('/').filter(Boolean)[0]||'home';let category='All',search='';
if(route==='home')$('#main').innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">SIALKOT DA SWAAD · ALAM CHOWK</span><span class="punjabi-greeting" lang="pa-Arab" dir="rtl">جی آیاں نوں</span><h1>DESI DIL.<br><em>PUNJABI SOUL.</em></h1><p>A little smoke. A little spice. A whole lot of pyaar.<br>Pull up a chair for sajji, sizzling karahi, and a proper desi feast.</p><div class="hero-buttons"><a href="/menu/" class="button">EXPLORE THE MENU ↗</a><a href="/menu/?category=Platters" class="text-link">MAKE IT A FEAST ↗</a></div><div class="hero-footnote"><span>SAJJI · BBQ · KARAHI</span><span>NOON TO 4 AM, EVERY DAY</span></div></div><div class="hero-art"><img class="art-flower flower-left" src="/assets/truck-flower.svg" alt="" aria-hidden="true"><img class="art-flower flower-right" src="/assets/truck-flower.svg" alt="" aria-hidden="true"><span class="art-stars" aria-hidden="true">✦</span><img class="hero-dish" ${photo("/assets/food-ai/chicken-sajji.webp")} alt="Illustration of golden roasted chicken sajji with basmati rice" width="1200" height="1200" fetchpriority="high"><div class="platter-label"><span>GOOD FOOD. APNAY LOG.</span><strong>Our Signature Sajji</strong></div><div class="hero-seal">CHASKA<br>✦<br>DESI DA</div></div></section>${border}<div class="quick-strip"><div><span>01 /</span> SAJJI & BBQ</div><div><span>02 /</span> KARAHI COMFORT</div><div><span>03 /</span> PLATTERS TO SHARE</div></div>${discovery}<section class="section"><div class="section-heading"><div><span class="eyebrow">DIL KHOL KE KHAO</span><h2>BIG FLAVOURS.<br><span>VADDA PYAAR.</span></h2></div><a class="text-link" href="/menu/">THE FULL MENU ↗</a></div><div class="food-grid">${(items.filter(p=>p.featured).length?items.filter(p=>p.featured).slice(0,live?.settings?.homepage?.featured_count||3):items.slice(0,live?.settings?.homepage?.featured_count||3)).map(card).join('')}</div><p class="caption">Menu images are illustrative. Portions and presentation may vary. Prices are confirmed at checkout.</p></section><div class="ticker">SAJJI <span>✦</span> KARAHI <span>✦</span> YAARI <span>✦</span> Bunty سجی</div>${story}${deliveryZones}${cta}`;
else if(route==='menu'){ const requested=new URLSearchParams(location.search).get('category');if(items.some(p=>p.category===requested))category=requested;
 $('#main').innerHTML=intro('THE Bunty سجی MENU','PICK YOUR<br><em>DESI FAVOURITE.</em>','Sajji, karahi, BBQ and a little of everything you love. Find your favourite, choose a portion, and build your bag.')+`<section class="section"><div class="menu-tools"><div class="categories" aria-label="Menu categories">${['All',...new Set(items.map(p=>p.category))].map(c=>`<button data-category="${esc(c)}" aria-pressed="${c===category}">${esc(c)}</button>`).join('')}</div><input type="search" id="search" placeholder="Search your cravings…" aria-label="Search menu"></div><p id="result-count" class="caption" aria-live="polite"></p><div id="menu-grid" class="food-grid"></div><p class="caption">Menu images are illustrative; portions and presentation may vary. Prices and availability are checked again at checkout. Choose delivery or takeaway, then pay cash.</p></section>`;renderMenu();$('#search').addEventListener('input',e=>{search=e.target.value;renderMenu()});
}else if(route==='checkout'){await window.Commerce.checkout();}else if(route==='order'){await window.Commerce.tracking();}else if(route==='about')$('#main').innerHTML=intro('OUR KIND OF GOOD FOOD','ROOTED IN FLAVOUR.<br><em>MADE FOR SHARING.</em>','For the family catch-up, the friends’ feast, and every “bas ek aur bite” in between.')+story+deliveryZones+`<section class="section values"><article><span>✦</span><h3>THE DESI CLASSICS</h3><p>Sajji, karahi, BBQ and familiar flavours that bring a table together.</p></article><article><span>❋</span><h3>YOUR KIND OF PORTION</h3><p>A quarter sajji for your craving, or a platter for the whole crew. Choose what fits your table.</p></article><article><span>♡</span><h3>BETTER TOGETHER</h3><p>Couple, family and friends platters make choosing a shared meal a little easier.</p></article></section>`+cta;else if(route==='gallery')$('#main').innerHTML=intro('STRAIGHT FROM THE MENU','TAKE A<br><em>CLOSER LOOK.</em>','Browse all six original menu sheets. Tap to zoom. Current opening hours: daily, noon to 4 am (next day).')+`<section class="section gallery-grid">${[['menu-1','Welcome to Bunty سجی'],['menu-2','Sajji, fish & BBQ'],['menu-3','Kabab, chicken karahi & handi'],['menu-4','Beef karahi, tawa & sides'],['menu-5','Rolls, burgers, drinks & tandoor'],['menu-6','Platters & special deals']].map(([s,n])=>`<button class="gallery-card" data-image="${s}" data-title="${n}"><img src="/assets/${s}.jpg" alt="${n} original menu" loading="lazy"><span>${n} ↗</span></button>`).join('')}</section>`+cta;
else $('#main').innerHTML=intro('PAGE NOT FOUND','A LITTLE<br><em>OFF THE MENU.</em>','Let’s get you back to the good food.')+'<section class="section"><a class="button" href="/">BACK TO HOME ↗</a></section>';
function renderMenu(){const found=items.filter(p=>(category==='All'||p.category===category)&&(p.name+' '+p.description).toLowerCase().includes(search.toLowerCase().trim()));$('#menu-grid').innerHTML=found.length?found.map(card).join(''):'<p class="no-results">No dishes found. Try another name or category.</p>';$('#result-count').textContent=found.length+' dishes';}
function save(){document.querySelector('#bag-count').textContent=B.count();}
function renderBag(){save();document.querySelector('#bag-content').innerHTML=B.cart.length?B.entries().map(x=>`<div class="bag-row"><div><h3>${esc(x.item?.name||'Removed dish')}</h3><p>${esc(x.variant?.name||'Unavailable portion')} · ${money(x.price)}</p><p>${x.addons.map(a=>esc(a?.name||'Removed add-on')).join(', ')}</p>${x.available?'':'<p class="form-error">This selection is unavailable. Remove it to continue.</p>'}<div class="quantity"><button data-qty="${x.index}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${x.quantity}</span><button data-qty="${x.index}" data-delta="1" aria-label="Increase quantity" ${x.quantity===99?'disabled':''}>+</button><button class="remove" data-remove="${x.index}">Remove</button></div></div><strong>${money(x.total)}</strong></div>`).join('')+`<div class="total"><span>Subtotal</span><span>${money(B.subtotal())}</span></div><p class="small-note">Delivery charges and final total are shown after choosing your area at checkout. Takeaway has no delivery fee.</p><div class="bag-checkout"><a class="button" href="/checkout">CONTINUE TO CHECKOUT ↗</a></div>`:'<p class="empty">Your bag is empty. <a href="/menu/">Explore the menu ↗</a></p>';}
window.addEventListener('cartchange',()=>{save();if(document.querySelector('#bag-dialog').open)renderBag();});
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2500)}
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-add]');if(b&&!b.disabled){const p=items.find(x=>String(x.id)===b.dataset.add),card=b.closest('.food-card'),variant=+(card.querySelector('select')?.value||0);try{B.add(p.id,p.variant_ids[variant],[...card.querySelectorAll('[data-addon]:checked')].map(a=>a.dataset.addon));toast(p.name+' added to your bag');}catch(err){toast(err.message);}return}
 if(e.target.closest('[data-bag]')){renderBag();$('#bag-dialog').showModal()}
 const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();
 const q=e.target.closest('[data-qty]');if(q){B.quantity(+q.dataset.qty,+q.dataset.delta);renderBag()}
 const r=e.target.closest('[data-remove]');if(r){B.remove(+r.dataset.remove);renderBag()}
 const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;const url=new URL(location.href);if(category==='All')url.searchParams.delete('category');else url.searchParams.set('category',category);history.replaceState(null,'',url);document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',b===c));renderMenu()}
 const img=e.target.closest('[data-image]');if(img){$('#full-image').src='/assets/'+img.dataset.image+'.jpg';$('#full-image').alt=img.dataset.title+' original menu';$('#image-dialog').showModal()}
});
const toggle=$('.mobile-toggle');toggle.onclick=()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',open);$('nav').classList.toggle('open',open)};document.addEventListener('keydown',e=>{if(e.key==='Escape'){toggle.setAttribute('aria-expanded','false');$('nav').classList.remove('open')}});
document.querySelectorAll('nav a').forEach(a=>{if(!new URL(a.href).hash&&new URL(a.href).pathname===location.pathname)a.setAttribute('aria-current','page')});$('#year').textContent=new Date().getFullYear();save();

document.addEventListener('change',e=>{if(e.target.matches('[data-variant]')){const p=items.find(x=>String(x.id)===e.target.dataset.variant);e.target.closest('.food-card').querySelector('[data-price]').textContent=money(p.variants[+e.target.value][1]);}});

window.publicReady=true;
window.Storefront.enhance(live).catch(()=>{});

// Keep entrance motion brief, and leave content visible without JavaScript support.
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
if('IntersectionObserver' in window&&!reducedMotion.matches&&live?.settings?.homepage?.animations!==false){
 const revealObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.remove('pending');revealObserver.unobserve(entry.target);}},{threshold:.08});
 document.querySelectorAll('.section-heading,.story-copy,.visit-intro,.discovery-heading,.food-card,.category-tile,.deal-card').forEach(el=>{el.classList.add('scroll-reveal');revealObserver.observe(el);});
 reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches){document.querySelectorAll('.pending').forEach(el=>el.classList.remove('pending'));revealObserver.disconnect();}});
}
const siteHeader=document.querySelector('header');
const updateHeader=()=>siteHeader.classList.toggle('scrolled',scrollY>15);
window.addEventListener('scroll',updateHeader,{passive:true});updateHeader();
document.addEventListener('click',e=>{if(e.target.closest('[data-add]')){const bag=document.querySelector('.bag');bag.classList.remove('bump');requestAnimationFrame(()=>bag.classList.add('bump'));}if(e.target.closest('nav a')){toggle.setAttribute('aria-expanded','false');document.querySelector('nav').classList.remove('open');}});

if(!live){const note=document.createElement('p');note.className='setup-notice';note.innerHTML='Online ordering is temporarily unavailable. This is a preview menu. <button type="button" data-retry>RETRY CONNECTION</button> or call 052 3242 312.';document.querySelector('#main').prepend(note);}
if(live){const s=live.settings;document.title=s.name+' — Bunty سجی';document.querySelector('.visit-intro>p').textContent=s.name;document.querySelector('.visit-details').innerHTML=`<div><span class="eyebrow">FIND US</span><address>${esc(s.address)}</address></div><div><span class="eyebrow">OPENING HOURS</span><p>${esc(s.opening_hours)}</p></div><div><span class="eyebrow">LET’S TALK FOOD</span><a class="phone-link" href="tel:${esc((s.phone||'052 3242 312').replace(/[^+0-9]/g,''))}">${esc(s.phone||'052 3242 312')}</a><a class="contact-link" href="https://wa.me/${esc((s.whatsapp||'').replace(/[^0-9]/g,''))}" target="_blank" rel="noopener noreferrer"><span class="whatsapp-badge">WhatsApp</span>${esc(s.whatsapp)} ↗</a><a class="contact-link" href="https://wa.me/${esc((s.whatsapp2||'').replace(/[^0-9]/g,''))}" target="_blank" rel="noopener noreferrer"><span class="whatsapp-badge">WhatsApp</span>${esc(s.whatsapp2)} ↗</a><a class="contact-link" href="mailto:${esc(s.email||'Buntysajjisialkot@gmail.com')}"><span aria-hidden="true">✉</span> ${esc(s.email||'Buntysajjisialkot@gmail.com')}</a><div class="settings-social">${['instagram','facebook','tiktok','youtube'].filter(k=>s[k]).map(k=>`<a href="${esc(s[k])}" target="_blank" rel="noopener noreferrer">${k}</a>`).join('')}</div></div>`;document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.href='tel:'+(s.phone||'052 3242 312').replace(/[^+0-9]/g,''));document.querySelectorAll('a[href*="google.com/maps"]').forEach(a=>a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.name+' '+s.address));document.querySelector('.topline>span').textContent=s.opening_hours;const hours=document.querySelector('.hero-footnote span:last-child');if(hours)hours.textContent=s.opening_hours;}
})();
