import 'dotenv/config';
import {test,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {randomBytes} from 'node:crypto';
const secret=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
test.skip(!secret,'A real Supabase server key is required for hosted end-to-end tests.');
test('real Supabase admin CRUD, upload, delivery COD, takeaway cash, tracking and authorization',async({page,browser})=>{
 const db=createClient(process.env.SUPABASE_URL,secret,{auth:{persistSession:false,autoRefreshToken:false}});
 const stamp=Date.now(),email=`bunty-qa-${stamp}@example.invalid`,password=randomBytes(24).toString('base64url'),categoryName=`QA Category ${stamp}`,dishName=`QA Sajji ${stamp}`,zoneName=`QA Zone ${stamp}`,customerName=`QA Customer ${stamp}`;
 let userId,outsiderId,uploadedPath,originalSettings;const errors=[];page.on('pageerror',err=>errors.push(err.message));
 const customer=await browser.newContext({baseURL:'http://127.0.0.1:3100'}),shop=await customer.newPage();shop.on('pageerror',err=>errors.push(err.message));
 try{
  const auth=await db.auth.admin.createUser({email,password,email_confirm:true});if(auth.error)throw auth.error;userId=auth.data.user.id;
  const profile=await db.from('admin_profiles').insert({user_id:userId,role:'admin',active:true});if(profile.error)throw profile.error;
  originalSettings=(await db.from('restaurant_settings').select('*').eq('id',1).single()).data;
  await shop.goto('/admin/orders');await expect(shop).toHaveURL(/\/admin\/login/);
  const denied=await customer.request.get('/api/admin/orders');expect(denied.status()).toBe(401);
  await page.goto('/admin/login');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'SIGN IN',exact:true}).click();await expect(page.locator('#login-error')).toContainText('incorrect');
  await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'SIGN IN',exact:true}).click();await expect(page).toHaveURL(/\/admin$/);await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible();
  const cookies=await page.context().cookies();expect(cookies.find(c=>c.name==='bs_access').httpOnly).toBe(true);expect(cookies.find(c=>c.name==='bs_access').sameSite).toBe('Strict');
  await page.getByRole('link',{name:'Categories',exact:true}).click();await page.getByRole('button',{name:'ADD CATEGORY',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill(categoryName);await page.getByRole('button',{name:'SAVE CATEGORY',exact:true}).click();await expect(page.locator('.admin-table')).toContainText(categoryName);
  await page.getByRole('link',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'ADD FOOD ITEM',exact:true}).click();await page.getByLabel('Dish name',{exact:true}).fill(dishName);await page.getByLabel('Category',{exact:true}).selectOption({label:categoryName});await page.getByLabel('Description',{exact:true}).fill('Temporary QA menu item; removed after testing.');await page.locator('#variant-list [data-option-price]').fill('500');
  await page.getByRole('button',{name:'ADD VARIANT',exact:true}).click();await page.locator('#variant-list .option-row').nth(1).locator('[data-option-name]').fill('Large');await page.locator('#variant-list .option-row').nth(1).locator('[data-option-price]').fill('900');
  await page.getByRole('button',{name:'ADD ADD-ON',exact:true}).click();await page.locator('#addon-list [data-option-name]').fill('Extra raita');await page.locator('#addon-list [data-option-price]').fill('50');
  await page.locator('#photo-upload').setInputFiles('assets/food/sajji.webp');await expect(page.locator('#upload-status')).toContainText('Photo uploaded');const url=await page.locator('[name=image_url]').inputValue();uploadedPath=url.split('/food-images/')[1];expect(uploadedPath).toBeTruthy();
  await page.getByRole('button',{name:'SAVE DISH',exact:true}).click();await expect(page.locator('.admin-table')).toContainText(dishName);
  await page.locator('tr').filter({hasText:dishName}).getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#variant-list [data-option-price]').first().fill('550');await page.getByRole('button',{name:'SAVE DISH',exact:true}).click();await expect(page.locator('tr').filter({hasText:dishName})).toContainText('550');
  await page.getByRole('link',{name:'Delivery zones',exact:true}).click();await page.getByRole('button',{name:'ADD DELIVERY ZONE',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill(zoneName);await page.getByLabel('Delivery fee (Rs.)',{exact:true}).fill('100');await page.getByLabel('Minimum order (Rs.)',{exact:true}).fill('500');await page.getByLabel('Estimated delivery minutes',{exact:true}).fill('45');await page.getByRole('button',{name:'SAVE ZONE',exact:true}).click();await expect(page.locator('.admin-table')).toContainText(zoneName);
  await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByLabel('Accept delivery orders',{exact:true}).check();await page.getByLabel('Accept takeaway orders',{exact:true}).check();await page.getByRole('button',{name:'SAVE SETTINGS',exact:true}).click();await expect(page.locator('#admin-message')).toContainText('Saved successfully');
  await shop.goto('/menu/');await shop.getByRole('searchbox',{name:'Search menu'}).fill(dishName);await expect(shop.locator('.food-card')).toHaveCount(1);await shop.locator('[data-addon]').check();await shop.locator('[data-add]').click();await shop.reload();await expect(shop.locator('#bag-count')).toHaveText('1');await shop.locator('[data-bag]').click();await expect(shop.locator('#bag-content')).toContainText('Extra raita');await shop.getByRole('link',{name:'CONTINUE TO CHECKOUT'}).click();
  await shop.getByLabel('Full name',{exact:true}).fill(customerName);await shop.getByLabel('Phone number',{exact:true}).fill('03001234567');await shop.getByLabel('Delivery area',{exact:true}).selectOption({label:`${zoneName} · Rs. 100`});await shop.getByLabel('Full delivery address',{exact:true}).fill('QA-only address, not a real delivery');await expect(shop.locator('#checkout-totals .grand-total')).toContainText('700');await shop.getByRole('button',{name:'PLACE ORDER',exact:true}).click();await expect(shop).toHaveURL(/\/order\/BS-\d+#/);await expect(shop.locator('#tracking-content')).toContainText('cash on delivery');await expect(shop.locator('#tracking-content')).toContainText('Rs. 700');const deliveryLink=shop.url(),number=new URL(deliveryLink).pathname.split('/')[2];
  const wrongToken=await customer.request.get(`/api/orders/${number}`,{headers:{Authorization:'Bearer '+'0'.repeat(64)}});expect(wrongToken.status()).toBe(404);
  await page.getByRole('link',{name:'Orders',exact:true}).click();await page.locator('#order-search').fill(number);await page.locator('tr').filter({hasText:number}).getByRole('button',{name:'View order',exact:true}).click();await expect(page.locator('#order-detail')).toContainText(customerName);
  for(const status of ['confirmed','preparing','out_for_delivery','completed']){await page.locator('#status-form select').selectOption(status);await page.getByRole('button',{name:'UPDATE STATUS',exact:true}).click();await expect(page.locator('#order-detail')).toContainText(`Current status: ${status.replaceAll('_',' ')}`);if(status==='confirmed')await expect(shop.locator('.tracking-status h2')).toHaveText('confirmed',{timeout:20000});}
  await shop.getByRole('button',{name:'REFRESH STATUS',exact:true}).click();await expect(shop.locator('.tracking-status h2')).toHaveText('completed');await expect(shop.locator('.tracking-status')).toContainText('Payment paid');
  await shop.goto('/menu/');await shop.getByRole('searchbox',{name:'Search menu'}).fill(dishName);await shop.locator('[data-variant]').selectOption({label:'Large · Rs. 900'});await shop.locator('[data-add]').click();await shop.goto('/checkout');await shop.getByLabel('Takeaway',{exact:false}).check();await shop.getByLabel('Full name',{exact:true}).fill(customerName);await shop.getByLabel('Phone number',{exact:true}).fill('03001234567');await expect(shop.locator('#checkout-totals .grand-total')).toContainText('900');await expect(shop.locator('#payment-notice')).toHaveText('Payment: Cash on Pickup');await shop.getByRole('button',{name:'PLACE ORDER',exact:true}).click();await expect(shop).toHaveURL(/\/order\/BS-\d+#/);await expect(shop.locator('#tracking-content')).toContainText('cash on pickup');const pickupNumber=new URL(shop.url()).pathname.split('/')[2];
  await page.locator('#order-search').fill(pickupNumber);await page.locator('tr').filter({hasText:pickupNumber}).getByRole('button',{name:'View order',exact:true}).click();for(const status of ['confirmed','preparing','ready_for_pickup','completed']){await page.locator('#status-form select').selectOption(status);await page.getByRole('button',{name:'UPDATE STATUS',exact:true}).click();await expect(page.locator('#order-detail')).toContainText(`Current status: ${status.replaceAll('_',' ')}`);}await shop.getByRole('button',{name:'REFRESH STATUS',exact:true}).click();await expect(shop.locator('.tracking-status h2')).toHaveText('completed');
  await shop.setViewportSize({width:390,height:844});await shop.goto('/menu/');expect(await shop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shop.screenshot({path:'test-results/menu-mobile.png'});
  await page.getByRole('button',{name:'LOG OUT',exact:true}).click();await expect(page).toHaveURL(/\/admin\/login$/);await page.goto('/admin/settings');await expect(page).toHaveURL(/\/admin\/login$/);
  const outsider=await db.auth.admin.createUser({email:`bunty-no-admin-${stamp}@example.invalid`,password,email_confirm:true});if(outsider.error)throw outsider.error;outsiderId=outsider.data.user.id;const rejected=await customer.request.post('/api/auth/login',{headers:{Origin:'http://127.0.0.1:3100'},data:{email:outsider.data.user.email,password}});expect(rejected.status()).toBe(403);
  const csrf=await customer.request.post('/api/auth/login',{headers:{Origin:'https://evil.example'},data:{email,password}});expect(csrf.status()).toBe(403);expect(errors).toEqual([]);
 }finally{
  await customer.close();
  const check=async promise=>{const {error}=await promise;if(error)throw error;};
  await check(db.from('orders').delete().eq('customer_name',customerName));
  await check(db.from('menu_items').delete().eq('name',dishName));
  await check(db.from('categories').delete().eq('name',categoryName));
  await check(db.from('delivery_zones').delete().eq('name',zoneName));
  if(originalSettings)await check(db.from('restaurant_settings').update({delivery_enabled:originalSettings.delivery_enabled,takeaway_enabled:originalSettings.takeaway_enabled}).eq('id',1));
  if(uploadedPath)await check(db.storage.from('food-images').remove([uploadedPath]));
  if(userId)await check(db.auth.admin.deleteUser(userId));if(outsiderId)await check(db.auth.admin.deleteUser(outsiderId));
 }
});
