import {cpSync,mkdirSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
execFileSync(process.execPath,['scripts/build.mjs'],{stdio:'inherit'});
const destination='release/server-app';
mkdirSync(destination,{recursive:true});
for(const file of ['package.json','package-lock.json','.env.example','README.md','LAUNCH.md','docs','server','dist','index.html','404.html','admin.html','app.js','menu-data.js','style.css','enhancements.css','punjabi-theme.css','system.css','assets','client','menu','about','gallery'])cpSync(file,`${destination}/${file}`,{recursive:true});
mkdirSync(`${destination}/scripts`,{recursive:true});
for(const file of ['build.mjs','create-admin.mjs','generate-seed.mjs'])cpSync(`scripts/${file}`,`${destination}/scripts/${file}`);
mkdirSync(`${destination}/supabase`,{recursive:true});
cpSync('supabase/migrations',`${destination}/supabase/migrations`,{recursive:true});cpSync('supabase/seed.sql',`${destination}/supabase/seed.sql`);
writeFileSync(`${destination}/DEPLOYMENT.txt`,'Run this project with Node, not a static-only upload. Set server environment variables, run npm ci --omit=dev, npm run build, then npm start. See LAUNCH.md. No secrets are included.\n');
console.log('Node deployment files prepared in release/server-app. Configure Supabase environment variables before starting.');
